---
author: "Lorena Pantano"
title: "How to create templates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pkgdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This repository is for internal use, so any kind of 
script or template will be helpful to others.
They don't need to be a final product, so go ahead and add
anything you did that we don't have automatized.

# R scripts

Scripts are being stored in `inst/rmarkdown/Rscripts`:

* Create a folder that categorize the analysis if it is not there.
* Create a R file that contains your code
* If you add the first line with a description: `# this is for alternative splicing with IRFinder`, it will be used as a description of the script in the page where all templates/scripts are being listed.

# Rmarkdown 

How to add new templates to HBC repository in 30 lines.

First you need to clone [hbcABC](https://github.com/hbc/hbcABC) repo to your computer.

After that, the easiest way to create templates is to follow this structure.

Inside the folder `inst/rmarkdown/templates` create a folder with the name of the RMD template you want to add, for instance: `hello_word_rmd`.

Then, create a YAML file named `template.yaml` with the following information:

```
name: Name of the template
description: >
  Description that will be shown in Rstudio.
create_dir: false
```
 
Create another folder named: `skeleton` and inside this a RMD file named `skeleton.Rmd` containing the rmarkdown you want to add.

At the end you'll should have this folders tree under `inst/rmarkdown`:

```
templates
-- hello_world_rmd
---- template.yaml
---- skeleton
------- skeleton.Rmd
```

To test it, install the package and go to the `File` -> `New File` -> `R Markdown` and click on templates. Your new template should be there.
